name: Test
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: "Test runner"
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: '${{ secrets.UNITY_LICENSE }}'
        with:
          projectPath: /Users/pradeep/Unity/Ball Launcher/ProjectSettings/ProjectSettings.asset
          githubToken: '${{ secrets.GITHUB_TOKEN }}'
